# ==============================================================================
# Docker Compose - Development Environment
# Faster rebuilds, hot reload, debugging tools
# ==============================================================================

version: '3.8'

services:
  # ==============================================================================
  # PostgreSQL Database
  # ==============================================================================
  db:
    image: postgres:16-alpine
    container_name: crm-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-crmuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crmpassword}
      POSTGRES_DB: ${POSTGRES_DB:-food_orders_crm}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crm-dev-network

  # ==============================================================================
  # Redis Cache
  # ==============================================================================
  redis:
    image: redis:7-alpine
    container_name: crm-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-devpassword}
    ports:
      - "6379:6379"
    networks:
      - crm-dev-network

  # ==============================================================================
  # Adminer - Database Management
  # ==============================================================================
  adminer:
    image: adminer:latest
    container_name: crm-adminer-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - crm-dev-network

networks:
  crm-dev-network:
    driver: bridge
    name: crm-dev-network

volumes:
  postgres_dev_data:
    name: crm-postgres-dev-data
